/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Define if s/key support is enabled */
//#define ENABLE_SKEY 1

/* Gettext package */
#define GETTEXT_PACKAGE "mate-terminal"

//#define HAVE_SMCLIENT 1

/* Name of package */
#define PACKAGE "mate-terminal"

/* Define to the full name of this package. */
#define PACKAGE_NAME "mate-terminal"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "mate-terminal 1.28.1.0"

/* Define to the home page for this package. */
#define PACKAGE_URL "https://mate-desktop.org"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.28.1"

/* Name of package */
#define VERSION "1.28.1"

