/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "nemo-generated.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

#ifdef G_ENABLE_DEBUG
#define g_marshal_value_peek_boolean(v)  g_value_get_boolean (v)
#define g_marshal_value_peek_char(v)     g_value_get_schar (v)
#define g_marshal_value_peek_uchar(v)    g_value_get_uchar (v)
#define g_marshal_value_peek_int(v)      g_value_get_int (v)
#define g_marshal_value_peek_uint(v)     g_value_get_uint (v)
#define g_marshal_value_peek_long(v)     g_value_get_long (v)
#define g_marshal_value_peek_ulong(v)    g_value_get_ulong (v)
#define g_marshal_value_peek_int64(v)    g_value_get_int64 (v)
#define g_marshal_value_peek_uint64(v)   g_value_get_uint64 (v)
#define g_marshal_value_peek_enum(v)     g_value_get_enum (v)
#define g_marshal_value_peek_flags(v)    g_value_get_flags (v)
#define g_marshal_value_peek_float(v)    g_value_get_float (v)
#define g_marshal_value_peek_double(v)   g_value_get_double (v)
#define g_marshal_value_peek_string(v)   (char*) g_value_get_string (v)
#define g_marshal_value_peek_param(v)    g_value_get_param (v)
#define g_marshal_value_peek_boxed(v)    g_value_get_boxed (v)
#define g_marshal_value_peek_pointer(v)  g_value_get_pointer (v)
#define g_marshal_value_peek_object(v)   g_value_get_object (v)
#define g_marshal_value_peek_variant(v)  g_value_get_variant (v)
#else /* !G_ENABLE_DEBUG */
/* WARNING: This code accesses GValues directly, which is UNSUPPORTED API.
 *          Do not access GValues directly in your code. Instead, use the
 *          g_value_get_*() functions
 */
#define g_marshal_value_peek_boolean(v)  (v)->data[0].v_int
#define g_marshal_value_peek_char(v)     (v)->data[0].v_int
#define g_marshal_value_peek_uchar(v)    (v)->data[0].v_uint
#define g_marshal_value_peek_int(v)      (v)->data[0].v_int
#define g_marshal_value_peek_uint(v)     (v)->data[0].v_uint
#define g_marshal_value_peek_long(v)     (v)->data[0].v_long
#define g_marshal_value_peek_ulong(v)    (v)->data[0].v_ulong
#define g_marshal_value_peek_int64(v)    (v)->data[0].v_int64
#define g_marshal_value_peek_uint64(v)   (v)->data[0].v_uint64
#define g_marshal_value_peek_enum(v)     (v)->data[0].v_long
#define g_marshal_value_peek_flags(v)    (v)->data[0].v_ulong
#define g_marshal_value_peek_float(v)    (v)->data[0].v_float
#define g_marshal_value_peek_double(v)   (v)->data[0].v_double
#define g_marshal_value_peek_string(v)   (v)->data[0].v_pointer
#define g_marshal_value_peek_param(v)    (v)->data[0].v_pointer
#define g_marshal_value_peek_boxed(v)    (v)->data[0].v_pointer
#define g_marshal_value_peek_pointer(v)  (v)->data[0].v_pointer
#define g_marshal_value_peek_object(v)   (v)->data[0].v_pointer
#define g_marshal_value_peek_variant(v)  (v)->data[0].v_pointer
#endif /* !G_ENABLE_DEBUG */

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  guint use_gvariant : 1;
  guint emits_changed_signal : 1;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

static void
_g_dbus_codegen_marshal_BOOLEAN__OBJECT_BOXED_STRING (
    GClosure     *closure,
    GValue       *return_value,
    unsigned int  n_param_values,
    const GValue *param_values,
    void         *invocation_hint G_GNUC_UNUSED,
    void         *marshal_data)
{
  typedef gboolean (*_GDbusCodegenMarshalBoolean_ObjectBoxedStringFunc)
       (void *data1,
        GDBusMethodInvocation *arg_method_invocation,
        const gchar *const *arg_SourceFilesURIList,
        const gchar *arg_DestinationDirectoryURI,
        void *data2);
  _GDbusCodegenMarshalBoolean_ObjectBoxedStringFunc callback;
  GCClosure *cc = (GCClosure*) closure;
  void *data1, *data2;
  gboolean v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 4);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = g_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = g_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }

  callback = (_GDbusCodegenMarshalBoolean_ObjectBoxedStringFunc)
    (marshal_data ? marshal_data : cc->callback);

  v_return =
    callback (data1,
              g_marshal_value_peek_object (param_values + 1),
              g_marshal_value_peek_boxed (param_values + 2),
              g_marshal_value_peek_string (param_values + 3),
              data2);

  g_value_set_boolean (return_value, v_return);
}

static void
_g_dbus_codegen_marshal_BOOLEAN__OBJECT (
    GClosure     *closure,
    GValue       *return_value,
    unsigned int  n_param_values,
    const GValue *param_values,
    void         *invocation_hint G_GNUC_UNUSED,
    void         *marshal_data)
{
  typedef gboolean (*_GDbusCodegenMarshalBoolean_ObjectFunc)
       (void *data1,
        GDBusMethodInvocation *arg_method_invocation,
        void *data2);
  _GDbusCodegenMarshalBoolean_ObjectFunc callback;
  GCClosure *cc = (GCClosure*) closure;
  void *data1, *data2;
  gboolean v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 2);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = g_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = g_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }

  callback = (_GDbusCodegenMarshalBoolean_ObjectFunc)
    (marshal_data ? marshal_data : cc->callback);

  v_return =
    callback (data1,
              g_marshal_value_peek_object (param_values + 1),
              data2);

  g_value_set_boolean (return_value, v_return);
}

static void
_g_dbus_codegen_marshal_BOOLEAN__OBJECT_STRING_STRING_STRING_STRING (
    GClosure     *closure,
    GValue       *return_value,
    unsigned int  n_param_values,
    const GValue *param_values,
    void         *invocation_hint G_GNUC_UNUSED,
    void         *marshal_data)
{
  typedef gboolean (*_GDbusCodegenMarshalBoolean_ObjectStringStringStringStringFunc)
       (void *data1,
        GDBusMethodInvocation *arg_method_invocation,
        const gchar *arg_SourceFileURI,
        const gchar *arg_SourceDisplayName,
        const gchar *arg_DestinationDirectoryURI,
        const gchar *arg_DestinationDisplayName,
        void *data2);
  _GDbusCodegenMarshalBoolean_ObjectStringStringStringStringFunc callback;
  GCClosure *cc = (GCClosure*) closure;
  void *data1, *data2;
  gboolean v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 6);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = g_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = g_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }

  callback = (_GDbusCodegenMarshalBoolean_ObjectStringStringStringStringFunc)
    (marshal_data ? marshal_data : cc->callback);

  v_return =
    callback (data1,
              g_marshal_value_peek_object (param_values + 1),
              g_marshal_value_peek_string (param_values + 2),
              g_marshal_value_peek_string (param_values + 3),
              g_marshal_value_peek_string (param_values + 4),
              g_marshal_value_peek_string (param_values + 5),
              data2);

  g_value_set_boolean (return_value, v_return);
}

/* ------------------------------------------------------------------------
 * Code for interface org.Nemo.FileOperations
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:NemoDBusFileOperations
 * @title: NemoDBusFileOperations
 * @short_description: Generated C code for the org.Nemo.FileOperations D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-Nemo-FileOperations.top_of_page">org.Nemo.FileOperations</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.Nemo.FileOperations ---- */

static const _ExtendedGDBusArgInfo _nemo_dbus_file_operations_method_info_copy_uris_IN_ARG_SourceFilesURIList =
{
  {
    -1,
    (gchar *) "SourceFilesURIList",
    (gchar *) "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _nemo_dbus_file_operations_method_info_copy_uris_IN_ARG_DestinationDirectoryURI =
{
  {
    -1,
    (gchar *) "DestinationDirectoryURI",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _nemo_dbus_file_operations_method_info_copy_uris_IN_ARG_pointers[] =
{
  &_nemo_dbus_file_operations_method_info_copy_uris_IN_ARG_SourceFilesURIList.parent_struct,
  &_nemo_dbus_file_operations_method_info_copy_uris_IN_ARG_DestinationDirectoryURI.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _nemo_dbus_file_operations_method_info_copy_uris =
{
  {
    -1,
    (gchar *) "CopyURIs",
    (GDBusArgInfo **) &_nemo_dbus_file_operations_method_info_copy_uris_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-copy-uris",
  FALSE
};

static const _ExtendedGDBusArgInfo _nemo_dbus_file_operations_method_info_move_uris_IN_ARG_SourceFilesURIList =
{
  {
    -1,
    (gchar *) "SourceFilesURIList",
    (gchar *) "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _nemo_dbus_file_operations_method_info_move_uris_IN_ARG_DestinationDirectoryURI =
{
  {
    -1,
    (gchar *) "DestinationDirectoryURI",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _nemo_dbus_file_operations_method_info_move_uris_IN_ARG_pointers[] =
{
  &_nemo_dbus_file_operations_method_info_move_uris_IN_ARG_SourceFilesURIList.parent_struct,
  &_nemo_dbus_file_operations_method_info_move_uris_IN_ARG_DestinationDirectoryURI.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _nemo_dbus_file_operations_method_info_move_uris =
{
  {
    -1,
    (gchar *) "MoveURIs",
    (GDBusArgInfo **) &_nemo_dbus_file_operations_method_info_move_uris_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-move-uris",
  FALSE
};

static const _ExtendedGDBusMethodInfo _nemo_dbus_file_operations_method_info_empty_trash =
{
  {
    -1,
    (gchar *) "EmptyTrash",
    NULL,
    NULL,
    NULL
  },
  "handle-empty-trash",
  FALSE
};

static const _ExtendedGDBusArgInfo _nemo_dbus_file_operations_method_info_copy_file_IN_ARG_SourceFileURI =
{
  {
    -1,
    (gchar *) "SourceFileURI",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _nemo_dbus_file_operations_method_info_copy_file_IN_ARG_SourceDisplayName =
{
  {
    -1,
    (gchar *) "SourceDisplayName",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _nemo_dbus_file_operations_method_info_copy_file_IN_ARG_DestinationDirectoryURI =
{
  {
    -1,
    (gchar *) "DestinationDirectoryURI",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _nemo_dbus_file_operations_method_info_copy_file_IN_ARG_DestinationDisplayName =
{
  {
    -1,
    (gchar *) "DestinationDisplayName",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _nemo_dbus_file_operations_method_info_copy_file_IN_ARG_pointers[] =
{
  &_nemo_dbus_file_operations_method_info_copy_file_IN_ARG_SourceFileURI.parent_struct,
  &_nemo_dbus_file_operations_method_info_copy_file_IN_ARG_SourceDisplayName.parent_struct,
  &_nemo_dbus_file_operations_method_info_copy_file_IN_ARG_DestinationDirectoryURI.parent_struct,
  &_nemo_dbus_file_operations_method_info_copy_file_IN_ARG_DestinationDisplayName.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _nemo_dbus_file_operations_method_info_copy_file =
{
  {
    -1,
    (gchar *) "CopyFile",
    (GDBusArgInfo **) &_nemo_dbus_file_operations_method_info_copy_file_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-copy-file",
  FALSE
};

static const GDBusMethodInfo * const _nemo_dbus_file_operations_method_info_pointers[] =
{
  &_nemo_dbus_file_operations_method_info_copy_uris.parent_struct,
  &_nemo_dbus_file_operations_method_info_move_uris.parent_struct,
  &_nemo_dbus_file_operations_method_info_empty_trash.parent_struct,
  &_nemo_dbus_file_operations_method_info_copy_file.parent_struct,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _nemo_dbus_file_operations_interface_info =
{
  {
    -1,
    (gchar *) "org.Nemo.FileOperations",
    (GDBusMethodInfo **) &_nemo_dbus_file_operations_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "file-operations",
};


/**
 * nemo_dbus_file_operations_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-Nemo-FileOperations.top_of_page">org.Nemo.FileOperations</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
nemo_dbus_file_operations_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_nemo_dbus_file_operations_interface_info.parent_struct;
}

/**
 * nemo_dbus_file_operations_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #NemoDBusFileOperations interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
nemo_dbus_file_operations_override_properties (GObjectClass *klass G_GNUC_UNUSED, guint property_id_begin)
{
  return property_id_begin - 1;
}


inline static void
nemo_dbus_file_operations_method_marshal_copy_uris (
    GClosure     *closure,
    GValue       *return_value,
    unsigned int  n_param_values,
    const GValue *param_values,
    void         *invocation_hint,
    void         *marshal_data)
{
  _g_dbus_codegen_marshal_BOOLEAN__OBJECT_BOXED_STRING (closure,
    return_value, n_param_values, param_values, invocation_hint, marshal_data);
}

inline static void
nemo_dbus_file_operations_method_marshal_move_uris (
    GClosure     *closure,
    GValue       *return_value,
    unsigned int  n_param_values,
    const GValue *param_values,
    void         *invocation_hint,
    void         *marshal_data)
{
  _g_dbus_codegen_marshal_BOOLEAN__OBJECT_BOXED_STRING (closure,
    return_value, n_param_values, param_values, invocation_hint, marshal_data);
}

inline static void
nemo_dbus_file_operations_method_marshal_empty_trash (
    GClosure     *closure,
    GValue       *return_value,
    unsigned int  n_param_values,
    const GValue *param_values,
    void         *invocation_hint,
    void         *marshal_data)
{
  _g_dbus_codegen_marshal_BOOLEAN__OBJECT (closure,
    return_value, n_param_values, param_values, invocation_hint, marshal_data);
}

inline static void
nemo_dbus_file_operations_method_marshal_copy_file (
    GClosure     *closure,
    GValue       *return_value,
    unsigned int  n_param_values,
    const GValue *param_values,
    void         *invocation_hint,
    void         *marshal_data)
{
  _g_dbus_codegen_marshal_BOOLEAN__OBJECT_STRING_STRING_STRING_STRING (closure,
    return_value, n_param_values, param_values, invocation_hint, marshal_data);
}


/**
 * NemoDBusFileOperations:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-Nemo-FileOperations.top_of_page">org.Nemo.FileOperations</link>.
 */

/**
 * NemoDBusFileOperationsIface:
 * @parent_iface: The parent interface.
 * @handle_copy_file: Handler for the #NemoDBusFileOperations::handle-copy-file signal.
 * @handle_copy_uris: Handler for the #NemoDBusFileOperations::handle-copy-uris signal.
 * @handle_empty_trash: Handler for the #NemoDBusFileOperations::handle-empty-trash signal.
 * @handle_move_uris: Handler for the #NemoDBusFileOperations::handle-move-uris signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-Nemo-FileOperations.top_of_page">org.Nemo.FileOperations</link>.
 */

typedef NemoDBusFileOperationsIface NemoDBusFileOperationsInterface;
G_DEFINE_INTERFACE (NemoDBusFileOperations, nemo_dbus_file_operations, G_TYPE_OBJECT)

static void
nemo_dbus_file_operations_default_init (NemoDBusFileOperationsIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * NemoDBusFileOperations::handle-copy-uris:
   * @object: A #NemoDBusFileOperations.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_SourceFilesURIList: Argument passed by remote caller.
   * @arg_DestinationDirectoryURI: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-Nemo-FileOperations.CopyURIs">CopyURIs()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nemo_dbus_file_operations_complete_copy_uris() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-copy-uris",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NemoDBusFileOperationsIface, handle_copy_uris),
    g_signal_accumulator_true_handled,
    NULL,
      nemo_dbus_file_operations_method_marshal_copy_uris,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRV, G_TYPE_STRING);

  /**
   * NemoDBusFileOperations::handle-move-uris:
   * @object: A #NemoDBusFileOperations.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_SourceFilesURIList: Argument passed by remote caller.
   * @arg_DestinationDirectoryURI: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-Nemo-FileOperations.MoveURIs">MoveURIs()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nemo_dbus_file_operations_complete_move_uris() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-move-uris",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NemoDBusFileOperationsIface, handle_move_uris),
    g_signal_accumulator_true_handled,
    NULL,
      nemo_dbus_file_operations_method_marshal_move_uris,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRV, G_TYPE_STRING);

  /**
   * NemoDBusFileOperations::handle-empty-trash:
   * @object: A #NemoDBusFileOperations.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-Nemo-FileOperations.EmptyTrash">EmptyTrash()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nemo_dbus_file_operations_complete_empty_trash() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-empty-trash",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NemoDBusFileOperationsIface, handle_empty_trash),
    g_signal_accumulator_true_handled,
    NULL,
      nemo_dbus_file_operations_method_marshal_empty_trash,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * NemoDBusFileOperations::handle-copy-file:
   * @object: A #NemoDBusFileOperations.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_SourceFileURI: Argument passed by remote caller.
   * @arg_SourceDisplayName: Argument passed by remote caller.
   * @arg_DestinationDirectoryURI: Argument passed by remote caller.
   * @arg_DestinationDisplayName: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-Nemo-FileOperations.CopyFile">CopyFile()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nemo_dbus_file_operations_complete_copy_file() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-copy-file",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NemoDBusFileOperationsIface, handle_copy_file),
    g_signal_accumulator_true_handled,
    NULL,
      nemo_dbus_file_operations_method_marshal_copy_file,
    G_TYPE_BOOLEAN,
    5,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING);

}

/**
 * nemo_dbus_file_operations_call_copy_uris:
 * @proxy: A #NemoDBusFileOperationsProxy.
 * @arg_SourceFilesURIList: Argument to pass with the method invocation.
 * @arg_DestinationDirectoryURI: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-Nemo-FileOperations.CopyURIs">CopyURIs()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nemo_dbus_file_operations_call_copy_uris_finish() to get the result of the operation.
 *
 * See nemo_dbus_file_operations_call_copy_uris_sync() for the synchronous, blocking version of this method.
 */
void
nemo_dbus_file_operations_call_copy_uris (
    NemoDBusFileOperations *proxy,
    const gchar *const *arg_SourceFilesURIList,
    const gchar *arg_DestinationDirectoryURI,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "CopyURIs",
    g_variant_new ("(^ass)",
                   arg_SourceFilesURIList,
                   arg_DestinationDirectoryURI),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nemo_dbus_file_operations_call_copy_uris_finish:
 * @proxy: A #NemoDBusFileOperationsProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nemo_dbus_file_operations_call_copy_uris().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nemo_dbus_file_operations_call_copy_uris().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nemo_dbus_file_operations_call_copy_uris_finish (
    NemoDBusFileOperations *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nemo_dbus_file_operations_call_copy_uris_sync:
 * @proxy: A #NemoDBusFileOperationsProxy.
 * @arg_SourceFilesURIList: Argument to pass with the method invocation.
 * @arg_DestinationDirectoryURI: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-Nemo-FileOperations.CopyURIs">CopyURIs()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nemo_dbus_file_operations_call_copy_uris() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nemo_dbus_file_operations_call_copy_uris_sync (
    NemoDBusFileOperations *proxy,
    const gchar *const *arg_SourceFilesURIList,
    const gchar *arg_DestinationDirectoryURI,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "CopyURIs",
    g_variant_new ("(^ass)",
                   arg_SourceFilesURIList,
                   arg_DestinationDirectoryURI),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nemo_dbus_file_operations_call_move_uris:
 * @proxy: A #NemoDBusFileOperationsProxy.
 * @arg_SourceFilesURIList: Argument to pass with the method invocation.
 * @arg_DestinationDirectoryURI: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-Nemo-FileOperations.MoveURIs">MoveURIs()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nemo_dbus_file_operations_call_move_uris_finish() to get the result of the operation.
 *
 * See nemo_dbus_file_operations_call_move_uris_sync() for the synchronous, blocking version of this method.
 */
void
nemo_dbus_file_operations_call_move_uris (
    NemoDBusFileOperations *proxy,
    const gchar *const *arg_SourceFilesURIList,
    const gchar *arg_DestinationDirectoryURI,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "MoveURIs",
    g_variant_new ("(^ass)",
                   arg_SourceFilesURIList,
                   arg_DestinationDirectoryURI),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nemo_dbus_file_operations_call_move_uris_finish:
 * @proxy: A #NemoDBusFileOperationsProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nemo_dbus_file_operations_call_move_uris().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nemo_dbus_file_operations_call_move_uris().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nemo_dbus_file_operations_call_move_uris_finish (
    NemoDBusFileOperations *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nemo_dbus_file_operations_call_move_uris_sync:
 * @proxy: A #NemoDBusFileOperationsProxy.
 * @arg_SourceFilesURIList: Argument to pass with the method invocation.
 * @arg_DestinationDirectoryURI: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-Nemo-FileOperations.MoveURIs">MoveURIs()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nemo_dbus_file_operations_call_move_uris() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nemo_dbus_file_operations_call_move_uris_sync (
    NemoDBusFileOperations *proxy,
    const gchar *const *arg_SourceFilesURIList,
    const gchar *arg_DestinationDirectoryURI,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "MoveURIs",
    g_variant_new ("(^ass)",
                   arg_SourceFilesURIList,
                   arg_DestinationDirectoryURI),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nemo_dbus_file_operations_call_empty_trash:
 * @proxy: A #NemoDBusFileOperationsProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-Nemo-FileOperations.EmptyTrash">EmptyTrash()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nemo_dbus_file_operations_call_empty_trash_finish() to get the result of the operation.
 *
 * See nemo_dbus_file_operations_call_empty_trash_sync() for the synchronous, blocking version of this method.
 */
void
nemo_dbus_file_operations_call_empty_trash (
    NemoDBusFileOperations *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "EmptyTrash",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nemo_dbus_file_operations_call_empty_trash_finish:
 * @proxy: A #NemoDBusFileOperationsProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nemo_dbus_file_operations_call_empty_trash().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nemo_dbus_file_operations_call_empty_trash().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nemo_dbus_file_operations_call_empty_trash_finish (
    NemoDBusFileOperations *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nemo_dbus_file_operations_call_empty_trash_sync:
 * @proxy: A #NemoDBusFileOperationsProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-Nemo-FileOperations.EmptyTrash">EmptyTrash()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nemo_dbus_file_operations_call_empty_trash() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nemo_dbus_file_operations_call_empty_trash_sync (
    NemoDBusFileOperations *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "EmptyTrash",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nemo_dbus_file_operations_call_copy_file:
 * @proxy: A #NemoDBusFileOperationsProxy.
 * @arg_SourceFileURI: Argument to pass with the method invocation.
 * @arg_SourceDisplayName: Argument to pass with the method invocation.
 * @arg_DestinationDirectoryURI: Argument to pass with the method invocation.
 * @arg_DestinationDisplayName: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-Nemo-FileOperations.CopyFile">CopyFile()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nemo_dbus_file_operations_call_copy_file_finish() to get the result of the operation.
 *
 * See nemo_dbus_file_operations_call_copy_file_sync() for the synchronous, blocking version of this method.
 */
void
nemo_dbus_file_operations_call_copy_file (
    NemoDBusFileOperations *proxy,
    const gchar *arg_SourceFileURI,
    const gchar *arg_SourceDisplayName,
    const gchar *arg_DestinationDirectoryURI,
    const gchar *arg_DestinationDisplayName,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "CopyFile",
    g_variant_new ("(ssss)",
                   arg_SourceFileURI,
                   arg_SourceDisplayName,
                   arg_DestinationDirectoryURI,
                   arg_DestinationDisplayName),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nemo_dbus_file_operations_call_copy_file_finish:
 * @proxy: A #NemoDBusFileOperationsProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nemo_dbus_file_operations_call_copy_file().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nemo_dbus_file_operations_call_copy_file().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nemo_dbus_file_operations_call_copy_file_finish (
    NemoDBusFileOperations *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nemo_dbus_file_operations_call_copy_file_sync:
 * @proxy: A #NemoDBusFileOperationsProxy.
 * @arg_SourceFileURI: Argument to pass with the method invocation.
 * @arg_SourceDisplayName: Argument to pass with the method invocation.
 * @arg_DestinationDirectoryURI: Argument to pass with the method invocation.
 * @arg_DestinationDisplayName: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-Nemo-FileOperations.CopyFile">CopyFile()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nemo_dbus_file_operations_call_copy_file() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
nemo_dbus_file_operations_call_copy_file_sync (
    NemoDBusFileOperations *proxy,
    const gchar *arg_SourceFileURI,
    const gchar *arg_SourceDisplayName,
    const gchar *arg_DestinationDirectoryURI,
    const gchar *arg_DestinationDisplayName,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "CopyFile",
    g_variant_new ("(ssss)",
                   arg_SourceFileURI,
                   arg_SourceDisplayName,
                   arg_DestinationDirectoryURI,
                   arg_DestinationDisplayName),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nemo_dbus_file_operations_complete_copy_uris:
 * @object: A #NemoDBusFileOperations.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-Nemo-FileOperations.CopyURIs">CopyURIs()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nemo_dbus_file_operations_complete_copy_uris (
    NemoDBusFileOperations *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * nemo_dbus_file_operations_complete_move_uris:
 * @object: A #NemoDBusFileOperations.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-Nemo-FileOperations.MoveURIs">MoveURIs()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nemo_dbus_file_operations_complete_move_uris (
    NemoDBusFileOperations *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * nemo_dbus_file_operations_complete_empty_trash:
 * @object: A #NemoDBusFileOperations.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-Nemo-FileOperations.EmptyTrash">EmptyTrash()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nemo_dbus_file_operations_complete_empty_trash (
    NemoDBusFileOperations *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * nemo_dbus_file_operations_complete_copy_file:
 * @object: A #NemoDBusFileOperations.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-Nemo-FileOperations.CopyFile">CopyFile()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nemo_dbus_file_operations_complete_copy_file (
    NemoDBusFileOperations *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * NemoDBusFileOperationsProxy:
 *
 * The #NemoDBusFileOperationsProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NemoDBusFileOperationsProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NemoDBusFileOperationsProxy.
 */

struct _NemoDBusFileOperationsProxyPrivate
{
  GData *qdata;
};

static void nemo_dbus_file_operations_proxy_iface_init (NemoDBusFileOperationsIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (NemoDBusFileOperationsProxy, nemo_dbus_file_operations_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (NemoDBusFileOperationsProxy)
                         G_IMPLEMENT_INTERFACE (NEMO_DBUS_TYPE_FILE_OPERATIONS, nemo_dbus_file_operations_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (NemoDBusFileOperationsProxy, nemo_dbus_file_operations_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (NEMO_DBUS_TYPE_FILE_OPERATIONS, nemo_dbus_file_operations_proxy_iface_init))

#endif
static void
nemo_dbus_file_operations_proxy_finalize (GObject *object)
{
  NemoDBusFileOperationsProxy *proxy = NEMO_DBUS_FILE_OPERATIONS_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (nemo_dbus_file_operations_proxy_parent_class)->finalize (object);
}

static void
nemo_dbus_file_operations_proxy_get_property (GObject      *object G_GNUC_UNUSED,
  guint         prop_id G_GNUC_UNUSED,
  GValue       *value G_GNUC_UNUSED,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
nemo_dbus_file_operations_proxy_set_property (GObject      *object G_GNUC_UNUSED,
  guint         prop_id G_GNUC_UNUSED,
  const GValue *value G_GNUC_UNUSED,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
nemo_dbus_file_operations_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_nemo_dbus_file_operations_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], NEMO_DBUS_TYPE_FILE_OPERATIONS);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, NEMO_DBUS_TYPE_FILE_OPERATIONS);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
nemo_dbus_file_operations_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  NemoDBusFileOperationsProxy *proxy = NEMO_DBUS_FILE_OPERATIONS_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nemo_dbus_file_operations_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nemo_dbus_file_operations_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
nemo_dbus_file_operations_proxy_init (NemoDBusFileOperationsProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = nemo_dbus_file_operations_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, NEMO_DBUS_TYPE_FILE_OPERATIONS_PROXY, NemoDBusFileOperationsProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), nemo_dbus_file_operations_interface_info ());
}

static void
nemo_dbus_file_operations_proxy_class_init (NemoDBusFileOperationsProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = nemo_dbus_file_operations_proxy_finalize;
  gobject_class->get_property = nemo_dbus_file_operations_proxy_get_property;
  gobject_class->set_property = nemo_dbus_file_operations_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = nemo_dbus_file_operations_proxy_g_signal;
  proxy_class->g_properties_changed = nemo_dbus_file_operations_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (NemoDBusFileOperationsProxyPrivate));
#endif
}

static void
nemo_dbus_file_operations_proxy_iface_init (NemoDBusFileOperationsIface *iface G_GNUC_UNUSED)
{
}

/**
 * nemo_dbus_file_operations_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-Nemo-FileOperations.top_of_page">org.Nemo.FileOperations</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nemo_dbus_file_operations_proxy_new_finish() to get the result of the operation.
 *
 * See nemo_dbus_file_operations_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
nemo_dbus_file_operations_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (NEMO_DBUS_TYPE_FILE_OPERATIONS_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.Nemo.FileOperations", NULL);
}

/**
 * nemo_dbus_file_operations_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nemo_dbus_file_operations_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with nemo_dbus_file_operations_proxy_new().
 *
 * Returns: (transfer full) (type NemoDBusFileOperationsProxy): The constructed proxy object or %NULL if @error is set.
 */
NemoDBusFileOperations *
nemo_dbus_file_operations_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return NEMO_DBUS_FILE_OPERATIONS (ret);
  else
    return NULL;
}

/**
 * nemo_dbus_file_operations_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-Nemo-FileOperations.top_of_page">org.Nemo.FileOperations</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See nemo_dbus_file_operations_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type NemoDBusFileOperationsProxy): The constructed proxy object or %NULL if @error is set.
 */
NemoDBusFileOperations *
nemo_dbus_file_operations_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (NEMO_DBUS_TYPE_FILE_OPERATIONS_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.Nemo.FileOperations", NULL);
  if (ret != NULL)
    return NEMO_DBUS_FILE_OPERATIONS (ret);
  else
    return NULL;
}


/**
 * nemo_dbus_file_operations_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like nemo_dbus_file_operations_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nemo_dbus_file_operations_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See nemo_dbus_file_operations_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
nemo_dbus_file_operations_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (NEMO_DBUS_TYPE_FILE_OPERATIONS_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.Nemo.FileOperations", NULL);
}

/**
 * nemo_dbus_file_operations_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nemo_dbus_file_operations_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with nemo_dbus_file_operations_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type NemoDBusFileOperationsProxy): The constructed proxy object or %NULL if @error is set.
 */
NemoDBusFileOperations *
nemo_dbus_file_operations_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return NEMO_DBUS_FILE_OPERATIONS (ret);
  else
    return NULL;
}

/**
 * nemo_dbus_file_operations_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like nemo_dbus_file_operations_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See nemo_dbus_file_operations_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type NemoDBusFileOperationsProxy): The constructed proxy object or %NULL if @error is set.
 */
NemoDBusFileOperations *
nemo_dbus_file_operations_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (NEMO_DBUS_TYPE_FILE_OPERATIONS_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.Nemo.FileOperations", NULL);
  if (ret != NULL)
    return NEMO_DBUS_FILE_OPERATIONS (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * NemoDBusFileOperationsSkeleton:
 *
 * The #NemoDBusFileOperationsSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NemoDBusFileOperationsSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NemoDBusFileOperationsSkeleton.
 */

struct _NemoDBusFileOperationsSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_nemo_dbus_file_operations_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  NemoDBusFileOperationsSkeleton *skeleton = NEMO_DBUS_FILE_OPERATIONS_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], NEMO_DBUS_TYPE_FILE_OPERATIONS);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, NEMO_DBUS_TYPE_FILE_OPERATIONS);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_nemo_dbus_file_operations_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  NemoDBusFileOperationsSkeleton *skeleton = NEMO_DBUS_FILE_OPERATIONS_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nemo_dbus_file_operations_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_nemo_dbus_file_operations_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  NemoDBusFileOperationsSkeleton *skeleton = NEMO_DBUS_FILE_OPERATIONS_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nemo_dbus_file_operations_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _nemo_dbus_file_operations_skeleton_vtable =
{
  _nemo_dbus_file_operations_skeleton_handle_method_call,
  _nemo_dbus_file_operations_skeleton_handle_get_property,
  _nemo_dbus_file_operations_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
nemo_dbus_file_operations_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return nemo_dbus_file_operations_interface_info ();
}

static GDBusInterfaceVTable *
nemo_dbus_file_operations_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_nemo_dbus_file_operations_skeleton_vtable;
}

static GVariant *
nemo_dbus_file_operations_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  NemoDBusFileOperationsSkeleton *skeleton = NEMO_DBUS_FILE_OPERATIONS_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_nemo_dbus_file_operations_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _nemo_dbus_file_operations_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _nemo_dbus_file_operations_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _nemo_dbus_file_operations_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.Nemo.FileOperations", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
nemo_dbus_file_operations_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton G_GNUC_UNUSED)
{
}

static void nemo_dbus_file_operations_skeleton_iface_init (NemoDBusFileOperationsIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (NemoDBusFileOperationsSkeleton, nemo_dbus_file_operations_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (NemoDBusFileOperationsSkeleton)
                         G_IMPLEMENT_INTERFACE (NEMO_DBUS_TYPE_FILE_OPERATIONS, nemo_dbus_file_operations_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (NemoDBusFileOperationsSkeleton, nemo_dbus_file_operations_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (NEMO_DBUS_TYPE_FILE_OPERATIONS, nemo_dbus_file_operations_skeleton_iface_init))

#endif
static void
nemo_dbus_file_operations_skeleton_finalize (GObject *object)
{
  NemoDBusFileOperationsSkeleton *skeleton = NEMO_DBUS_FILE_OPERATIONS_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (nemo_dbus_file_operations_skeleton_parent_class)->finalize (object);
}

static void
nemo_dbus_file_operations_skeleton_init (NemoDBusFileOperationsSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = nemo_dbus_file_operations_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, NEMO_DBUS_TYPE_FILE_OPERATIONS_SKELETON, NemoDBusFileOperationsSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
nemo_dbus_file_operations_skeleton_class_init (NemoDBusFileOperationsSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = nemo_dbus_file_operations_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = nemo_dbus_file_operations_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = nemo_dbus_file_operations_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = nemo_dbus_file_operations_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = nemo_dbus_file_operations_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (NemoDBusFileOperationsSkeletonPrivate));
#endif
}

static void
nemo_dbus_file_operations_skeleton_iface_init (NemoDBusFileOperationsIface *iface G_GNUC_UNUSED)
{
}

/**
 * nemo_dbus_file_operations_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-Nemo-FileOperations.top_of_page">org.Nemo.FileOperations</link>.
 *
 * Returns: (transfer full) (type NemoDBusFileOperationsSkeleton): The skeleton object.
 */
NemoDBusFileOperations *
nemo_dbus_file_operations_skeleton_new (void)
{
  return NEMO_DBUS_FILE_OPERATIONS (g_object_new (NEMO_DBUS_TYPE_FILE_OPERATIONS_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for Object, ObjectProxy and ObjectSkeleton
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:NemoDBusObject
 * @title: NemoDBusObject
 * @short_description: Specialized GDBusObject types
 *
 * This section contains the #NemoDBusObject, #NemoDBusObjectProxy, and #NemoDBusObjectSkeleton types which make it easier to work with objects implementing generated types for D-Bus interfaces.
 */

/**
 * NemoDBusObject:
 *
 * The #NemoDBusObject type is a specialized container of interfaces.
 */

/**
 * NemoDBusObjectIface:
 * @parent_iface: The parent interface.
 *
 * Virtual table for the #NemoDBusObject interface.
 */

typedef NemoDBusObjectIface NemoDBusObjectInterface;
G_DEFINE_INTERFACE_WITH_CODE (NemoDBusObject, nemo_dbus_object, G_TYPE_OBJECT, g_type_interface_add_prerequisite (g_define_type_id, G_TYPE_DBUS_OBJECT);)

static void
nemo_dbus_object_default_init (NemoDBusObjectIface *iface)
{
  /**
   * NemoDBusObject:file-operations:
   *
   * The #NemoDBusFileOperations instance corresponding to the D-Bus interface <link linkend="gdbus-interface-org-Nemo-FileOperations.top_of_page">org.Nemo.FileOperations</link>, if any.
   *
   * Connect to the #GObject::notify signal to get informed of property changes.
   */
  g_object_interface_install_property (iface, g_param_spec_object ("file-operations", "file-operations", "file-operations", NEMO_DBUS_TYPE_FILE_OPERATIONS, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

}

/**
 * nemo_dbus_object_get_file_operations:
 * @object: A #NemoDBusObject.
 *
 * Gets the #NemoDBusFileOperations instance for the D-Bus interface <link linkend="gdbus-interface-org-Nemo-FileOperations.top_of_page">org.Nemo.FileOperations</link> on @object, if any.
 *
 * Returns: (transfer full) (nullable): A #NemoDBusFileOperations that must be freed with g_object_unref() or %NULL if @object does not implement the interface.
 */
NemoDBusFileOperations *nemo_dbus_object_get_file_operations (NemoDBusObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.Nemo.FileOperations");
  if (ret == NULL)
    return NULL;
  return NEMO_DBUS_FILE_OPERATIONS (ret);
}


/**
 * nemo_dbus_object_peek_file_operations: (skip)
 * @object: A #NemoDBusObject.
 *
 * Like nemo_dbus_object_get_file_operations() but doesn't increase the reference count on the returned object.
 *
 * It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.
 *
 * Returns: (transfer none) (nullable): A #NemoDBusFileOperations or %NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
 */
NemoDBusFileOperations *nemo_dbus_object_peek_file_operations (NemoDBusObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.Nemo.FileOperations");
  if (ret == NULL)
    return NULL;
  g_object_unref (ret);
  return NEMO_DBUS_FILE_OPERATIONS (ret);
}


static void
nemo_dbus_object_notify (GDBusObject *object, GDBusInterface *interface)
{
  _ExtendedGDBusInterfaceInfo *info = (_ExtendedGDBusInterfaceInfo *) g_dbus_interface_get_info (interface);
  /* info can be NULL if the other end is using a D-Bus interface we don't know
   * anything about, for example old generated code in this process talking to
   * newer generated code in the other process. */
  if (info != NULL)
    g_object_notify (G_OBJECT (object), info->hyphen_name);
}

/**
 * NemoDBusObjectProxy:
 *
 * The #NemoDBusObjectProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NemoDBusObjectProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NemoDBusObjectProxy.
 */

static void
nemo_dbus_object_proxy__nemo_dbus_object_iface_init (NemoDBusObjectIface *iface G_GNUC_UNUSED)
{
}

static void
nemo_dbus_object_proxy__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = nemo_dbus_object_notify;
  iface->interface_removed = nemo_dbus_object_notify;
}


G_DEFINE_TYPE_WITH_CODE (NemoDBusObjectProxy, nemo_dbus_object_proxy, G_TYPE_DBUS_OBJECT_PROXY,
                         G_IMPLEMENT_INTERFACE (NEMO_DBUS_TYPE_OBJECT, nemo_dbus_object_proxy__nemo_dbus_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, nemo_dbus_object_proxy__g_dbus_object_iface_init))

static void
nemo_dbus_object_proxy_init (NemoDBusObjectProxy *object G_GNUC_UNUSED)
{
}

static void
nemo_dbus_object_proxy_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value G_GNUC_UNUSED,
  GParamSpec   *pspec)
{
  G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
}

static void
nemo_dbus_object_proxy_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  NemoDBusObjectProxy *object = NEMO_DBUS_OBJECT_PROXY (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.Nemo.FileOperations");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
nemo_dbus_object_proxy_class_init (NemoDBusObjectProxyClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = nemo_dbus_object_proxy_set_property;
  gobject_class->get_property = nemo_dbus_object_proxy_get_property;

  g_object_class_override_property (gobject_class, 1, "file-operations");
}

/**
 * nemo_dbus_object_proxy_new:
 * @connection: A #GDBusConnection.
 * @object_path: An object path.
 *
 * Creates a new proxy object.
 *
 * Returns: (transfer full): The proxy object.
 */
NemoDBusObjectProxy *
nemo_dbus_object_proxy_new (GDBusConnection *connection,
  const gchar *object_path)
{
  g_return_val_if_fail (G_IS_DBUS_CONNECTION (connection), NULL);
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return NEMO_DBUS_OBJECT_PROXY (g_object_new (NEMO_DBUS_TYPE_OBJECT_PROXY, "g-connection", connection, "g-object-path", object_path, NULL));
}

/**
 * NemoDBusObjectSkeleton:
 *
 * The #NemoDBusObjectSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NemoDBusObjectSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NemoDBusObjectSkeleton.
 */

static void
nemo_dbus_object_skeleton__nemo_dbus_object_iface_init (NemoDBusObjectIface *iface G_GNUC_UNUSED)
{
}


static void
nemo_dbus_object_skeleton__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = nemo_dbus_object_notify;
  iface->interface_removed = nemo_dbus_object_notify;
}

G_DEFINE_TYPE_WITH_CODE (NemoDBusObjectSkeleton, nemo_dbus_object_skeleton, G_TYPE_DBUS_OBJECT_SKELETON,
                         G_IMPLEMENT_INTERFACE (NEMO_DBUS_TYPE_OBJECT, nemo_dbus_object_skeleton__nemo_dbus_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, nemo_dbus_object_skeleton__g_dbus_object_iface_init))

static void
nemo_dbus_object_skeleton_init (NemoDBusObjectSkeleton *object G_GNUC_UNUSED)
{
}

static void
nemo_dbus_object_skeleton_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  NemoDBusObjectSkeleton *object = NEMO_DBUS_OBJECT_SKELETON (gobject);
  GDBusInterfaceSkeleton *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_value_get_object (value);
      if (interface != NULL)
        {
          g_warn_if_fail (NEMO_DBUS_IS_FILE_OPERATIONS (interface));
          g_dbus_object_skeleton_add_interface (G_DBUS_OBJECT_SKELETON (object), interface);
        }
      else
        {
          g_dbus_object_skeleton_remove_interface_by_name (G_DBUS_OBJECT_SKELETON (object), "org.Nemo.FileOperations");
        }
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
nemo_dbus_object_skeleton_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  NemoDBusObjectSkeleton *object = NEMO_DBUS_OBJECT_SKELETON (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.Nemo.FileOperations");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
nemo_dbus_object_skeleton_class_init (NemoDBusObjectSkeletonClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = nemo_dbus_object_skeleton_set_property;
  gobject_class->get_property = nemo_dbus_object_skeleton_get_property;

  g_object_class_override_property (gobject_class, 1, "file-operations");
}

/**
 * nemo_dbus_object_skeleton_new:
 * @object_path: An object path.
 *
 * Creates a new skeleton object.
 *
 * Returns: (transfer full): The skeleton object.
 */
NemoDBusObjectSkeleton *
nemo_dbus_object_skeleton_new (const gchar *object_path)
{
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return NEMO_DBUS_OBJECT_SKELETON (g_object_new (NEMO_DBUS_TYPE_OBJECT_SKELETON, "g-object-path", object_path, NULL));
}

/**
 * nemo_dbus_object_skeleton_set_file_operations:
 * @object: A #NemoDBusObjectSkeleton.
 * @interface_: (nullable): A #NemoDBusFileOperations or %NULL to clear the interface.
 *
 * Sets the #NemoDBusFileOperations instance for the D-Bus interface <link linkend="gdbus-interface-org-Nemo-FileOperations.top_of_page">org.Nemo.FileOperations</link> on @object.
 */
void nemo_dbus_object_skeleton_set_file_operations (NemoDBusObjectSkeleton *object, NemoDBusFileOperations *interface_)
{
  g_object_set (G_OBJECT (object), "file-operations", interface_, NULL);
}


/* ------------------------------------------------------------------------
 * Code for ObjectManager client
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:NemoDBusObjectManagerClient
 * @title: NemoDBusObjectManagerClient
 * @short_description: Generated GDBusObjectManagerClient type
 *
 * This section contains a #GDBusObjectManagerClient that uses nemo_dbus_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc.
 */

/**
 * NemoDBusObjectManagerClient:
 *
 * The #NemoDBusObjectManagerClient structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NemoDBusObjectManagerClientClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NemoDBusObjectManagerClient.
 */

G_DEFINE_TYPE (NemoDBusObjectManagerClient, nemo_dbus_object_manager_client, G_TYPE_DBUS_OBJECT_MANAGER_CLIENT)

static void
nemo_dbus_object_manager_client_init (NemoDBusObjectManagerClient *manager G_GNUC_UNUSED)
{
}

static void
nemo_dbus_object_manager_client_class_init (NemoDBusObjectManagerClientClass *klass G_GNUC_UNUSED)
{
}

/**
 * nemo_dbus_object_manager_client_get_proxy_type:
 * @manager: A #GDBusObjectManagerClient.
 * @object_path: The object path of the remote object (unused).
 * @interface_name: (nullable): Interface name of the remote object or %NULL to get the object proxy #GType.
 * @user_data: User data (unused).
 *
 * A #GDBusProxyTypeFunc that maps @interface_name to the generated #GDBusObjectProxy derived and #GDBusProxy derived types.
 *
 * Returns: A #GDBusProxy derived #GType if @interface_name is not %NULL, otherwise the #GType for #NemoDBusObjectProxy.
 */
GType
nemo_dbus_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager G_GNUC_UNUSED, const gchar *object_path G_GNUC_UNUSED, const gchar *interface_name, gpointer user_data G_GNUC_UNUSED)
{
  static gsize once_init_value = 0;
  static GHashTable *lookup_hash;
  GType ret;

  if (interface_name == NULL)
    return NEMO_DBUS_TYPE_OBJECT_PROXY;
  if (g_once_init_enter (&once_init_value))
    {
      lookup_hash = g_hash_table_new (g_str_hash, g_str_equal);
      g_hash_table_insert (lookup_hash, (gpointer) "org.Nemo.FileOperations", (gpointer) (guintptr) (NEMO_DBUS_TYPE_FILE_OPERATIONS_PROXY));
      g_once_init_leave (&once_init_value, 1);
    }
  ret = (GType) (guintptr) (g_hash_table_lookup (lookup_hash, interface_name));
  if (ret == (GType) 0)
    ret = G_TYPE_DBUS_PROXY;
  return ret;
}

/**
 * nemo_dbus_object_manager_client_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates #GDBusObjectManagerClient using nemo_dbus_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nemo_dbus_object_manager_client_new_finish() to get the result of the operation.
 *
 * See nemo_dbus_object_manager_client_new_sync() for the synchronous, blocking version of this constructor.
 */
void
nemo_dbus_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (NEMO_DBUS_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", nemo_dbus_object_manager_client_get_proxy_type, NULL);
}

/**
 * nemo_dbus_object_manager_client_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nemo_dbus_object_manager_client_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with nemo_dbus_object_manager_client_new().
 *
 * Returns: (transfer full) (type NemoDBusObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
nemo_dbus_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * nemo_dbus_object_manager_client_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates #GDBusObjectManagerClient using nemo_dbus_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See nemo_dbus_object_manager_client_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type NemoDBusObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
nemo_dbus_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (NEMO_DBUS_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", nemo_dbus_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


/**
 * nemo_dbus_object_manager_client_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like nemo_dbus_object_manager_client_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nemo_dbus_object_manager_client_new_for_bus_finish() to get the result of the operation.
 *
 * See nemo_dbus_object_manager_client_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
nemo_dbus_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (NEMO_DBUS_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", nemo_dbus_object_manager_client_get_proxy_type, NULL);
}

/**
 * nemo_dbus_object_manager_client_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nemo_dbus_object_manager_client_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with nemo_dbus_object_manager_client_new_for_bus().
 *
 * Returns: (transfer full) (type NemoDBusObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
nemo_dbus_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * nemo_dbus_object_manager_client_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like nemo_dbus_object_manager_client_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See nemo_dbus_object_manager_client_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type NemoDBusObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
nemo_dbus_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (NEMO_DBUS_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", nemo_dbus_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


