file(GLOB SANDBOX_FS_SRC
        ${CMAKE_SOURCE_DIR}/3thrd/fs/acls.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/attrib.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/attrlist.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/bitmap.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/bootsect.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/cache.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/collate.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/compat.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/compress.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/debug.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/device.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/dir.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/ea.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/efs.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/index.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/inode.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/ioctl.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/lcnalloc.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/logfile.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/logging.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/mft.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/misc.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/mst.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/object_id.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/realpath.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/reparse.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/runlist.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/security.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/unistr.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/unix_io.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/volume.c
        ${CMAKE_SOURCE_DIR}/3thrd/fs/xattrs.c
)